//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomelistiAPI.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomelistiDbEntities : DbContext
    {
        public HomelistiDbEntities()
            : base("name=HomelistiDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Choice> Choices { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CustomField> CustomFields { get; set; }
        public virtual DbSet<CustomFields_Choices> CustomFields_Choices { get; set; }
        public virtual DbSet<CustomFields_Values> CustomFields_Values { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Listing> Listings { get; set; }
        public virtual DbSet<Listings_CustomFields> Listings_CustomFields { get; set; }
        public virtual DbSet<ListingType> ListingTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Valuess> Valuesses { get; set; }
    }
}
