//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomelistiAPI.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ID { get; set; }
        public Nullable<int> listing_id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string alt { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
